# builtins.module

# builtins module is included by all opmodes!
#
# All names within this modules are available to all modules!

module

use telemetry
use modules
use labels
use cycle

type subr_t is subroutine
type label_t is label


subroutine init
    telemetry.report_string key: "builtins.init" value: "called"
    set isStarted? to: true?
    set isActive? to: true?
    return


label abort message$
    `fprintf(stderr, "%s\n", ` message$ `);`
    goto cycle.terminate 1

