# consumer.module

# use iter_types element_type
# use consumer iter_types c_yield c_done
#
# subroutine my_consumer p_config
#     var p_config is consumer.p_config_t
#     <init code>
#     goto consumer.start p_config
#  or goto consumer.start p_config alt_goto: somewhere_else
#  or consumer.ready p_config
#     <do something>
#     goto somewhere_else
#
#   label c_yield element
#     <process element>
#     goto consumer.p_next
#  or consumer.p_done
#     goto c_done
#
#   label c_done
#     return

module iter_types c_yield_orig c_done_orig
    -> ?new_p_next: new_p_next
    -> ?new_p_done: new_p_done
    -> ?new_p_config: new_p_config

var iter_types is module
var c_yield_orig is iter_types.c_yield_t      # linked(auto)
var c_done_orig is iter_types.c_done_t        # linked(auto)
var c_yield is iter_types.c_yield_t           # linked(auto)
var c_done is iter_types.c_done_t             # linked(auto)

var p_next is iter_types.p_next_t             # linked(auto)
var p_done is iter_types.p_done_t             # linked(auto)
var p_config is iter_types.p_config_t         # linked(auto)
var new_p_next is subroutine taking p_next: iter_types.p_next_t        # linked
var new_p_done is subroutine taking p_done: iter_types.p_done_t        # linked
var new_p_config is subroutine taking p_config: iter_types.p_config_t  # linked

# not reentrant
# (but what if new_p_next, new_p_done and/or new_p_config are reentrant)?
subroutine c_config ?p_next: p_next ?p_done: p_done ?p_config: p_config
    #telemetry.report_string key: {labels.get_subr_module_name$ c_config}
    #                     -> value: "c_config called"
    =================================================
    | YYN | got? p_next:              # params_passed and vars_set are auto
    | YN- | got? module.new_p_next:
    =================================================
    | X   | new_p_next p_next: p_next
    |  XX | continue
    =================================================
    =================================================
    | YYN | got? p_done:
    | YN- | got? module.new_p_done:
    =================================================
    | X   | new_p_done p_done: p_done
    |  XX | continue
    =================================================
    =================================================
    | YYN | got? p_config:
    | YN- | got? module.new_p_config:
    =================================================
    | X   | new_p_config p_config: p_config
    |  XX | #telemetry.report_string key: "c_config" value: "returning"
    |     | return
    =================================================


subroutine ready p_config                   # not reentrant
    #telemetry.report_string key: {labels.get_subr_module_name$ c_config}
    #                     -> value: "ready called"
    set c_yield to: c_yield_orig
    set c_done to: c_done_orig
    p_config c_yield: c_yield c_done: c_done c_config: c_config
    #telemetry.report_string key: {labels.get_subr_module_name$ c_config}
    #                     -> value: "ready returning"
    return


label start p_config ?alt_goto: alt_goto    # not reentrant
    var alt_goto is iter_types.p_next_t
    #telemetry.report_string key: {labels.get_subr_module_name$ c_config}
    #                     -> value: "start"
    ready p_config
    =================================================
    | YN | got? alt_goto:
    =================================================
    | X  | goto alt_goto
    |  X | goto p_next
    =================================================


subroutine new_c_yield c_yield: c_yield  # not reentrant
                                         # (but what if p_config is reentrant?)
    # This can only be called after ready or start has been called!
    # Otherwise, you'll get a p_config not set run-time error...

    #telemetry.report_string key: {labels.get_subr_module_name$ c_config}
    #                     -> value: "new_c_yield called"
    p_config c_yield: c_yield
    #telemetry.report_string key: "new_c_yield" value: "returning"
    return

subroutine new_c_done c_done: c_done     # not reentrant
                                         # (but what if p_config is reentrant?)
    # This can only be called after ready or start has been called!
    # Otherwise, you'll get a p_config not set run-time error...

    #telemetry.report_string key: {labels.get_subr_module_name$ c_config}
    #                     -> value: "new_c_done called"
    p_config c_done: c_done
    #telemetry.report_string key: "new_c_done" value: "returning"
    return

