# modules.module

module

use iter_types module
use producer iter_types p_next p_done


function gen_modules returning iter_types.p_config_t
    set imodule to: 0
    goto return_label producer.p_config
  
  label p_next
    ======================================================
    | YN | imodule < `__num_modules__`
    ======================================================
    | X  | set i to: imodule
    |    | imodule += 1
    |    | goto producer.c_yield (`__module_instances__[` i `]`)
    |  X | done
    |    | goto producer.c_done
    ======================================================

  subroutine p_done
    done with: gen_modules
    return


function get_module_name$ mod
    var mod is module
    return (`` mod `->name`)

function get_module_filename$ mod
    return (`` mod `->filename`)

