# stub_events.module

# Does not support any events.
#
# Provides a minimal set of interfaces for the timers module.
#


module


subroutine init_module
    return


subroutine reset
    return


function sleep_until secs nsecs
    # Returns true? if the timer expired before any other events happened.
    `errno = clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &Timespec, NULL);`
    =======================================================
    | NY | `errno` == 0
    =======================================================
    | X  | goto perror "events.sleep_until clock_nanosleep"
    |  X | return true?
    =======================================================


subroutine sleep_forever
    # This is only called when the only thing that will wake up the program
    # is an event.
    goto abort "events.sleep_foever called!"
